"""add vendor_id to quotation

Revision ID: 3267c5f395e9
Revises: 633f85eff68d
Create Date: 2026-02-01 01:47:33.244999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3267c5f395e9'
down_revision: Union[str, None] = '633f85eff68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('vendor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'quotations', 'users', ['vendor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'vendor_id')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    # ### end Alembic commands ###
