"""add_profile_photo_to_user

Revision ID: 508dc6cb0819
Revises: f9a8b7c6d5e4
Create Date: 2026-01-31 19:59:02.138337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '508dc6cb0819'
down_revision: Union[str, None] = 'f9a8b7c6d5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'quotations', ['quotation_number'])
    op.create_unique_constraint(None, 'rental_orders', ['order_number'])
    op.add_column('users', sa.Column('profile_photo', sa.String(), nullable=True))
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('users', 'referral_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('wallet_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='transactionstatus'),
               server_default=None,
               existing_nullable=True)
    op.execute(
        "DROP INDEX IF EXISTS ix_wallet_transactions_created_at"
    )
    op.execute("DROP INDEX IF EXISTS ix_wallet_transactions_wallet_id")
    op.alter_column('wallets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wallets', 'currency',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wallets', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('wallets', 'currency',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    op.alter_column('wallet_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='transactionstatus'),
               server_default=sa.text("'COMPLETED'::transactionstatus"),
               existing_nullable=True)
    op.alter_column('users', 'referral_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.drop_column('users', 'profile_photo')
    op.drop_constraint(None, 'rental_orders', type_='unique')
    op.drop_constraint(None, 'quotations', type_='unique')
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'invoices', type_='unique')
    # ### end Alembic commands ###
