"""add phone to users

Revision ID: 56bafcf031dd
Revises: e5f6a7b8c9d0
Create Date: 2026-01-31 19:10:04.322630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56bafcf031dd'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'quotations', ['quotation_number'])
    op.create_unique_constraint(None, 'rental_orders', ['order_number'])
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('users', 'referral_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('wallet_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='transactionstatus'),
               server_default=None,
               existing_nullable=True)
    # op.drop_index('ix_wallet_transactions_created_at', table_name='wallet_transactions')
    # op.drop_index('ix_wallet_transactions_wallet_id', table_name='wallet_transactions')
    op.alter_column('wallets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wallets', 'currency',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wallets', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('wallets', 'currency',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.create_index('ix_wallet_transactions_wallet_id', 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index('ix_wallet_transactions_created_at', 'wallet_transactions', ['created_at'], unique=False)
    op.alter_column('wallet_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='transactionstatus'),
               server_default=sa.text("'COMPLETED'::transactionstatus"),
               existing_nullable=True)
    op.alter_column('users', 'referral_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.drop_column('users', 'phone')
    op.drop_constraint(None, 'rental_orders', type_='unique')
    op.drop_constraint(None, 'quotations', type_='unique')
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'invoices', type_='unique')
    # ### end Alembic commands ###
