"""add wallet to payment method enum

Revision ID: 633f85eff68d
Revises: 8e540afd3a9f
Create Date: 2026-02-01 01:34:06.114142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633f85eff68d'
down_revision: Union[str, None] = '8e540afd3a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 1️⃣ Safely add WALLET to enum (only if missing)
    enum_values = conn.execute(
        sa.text("""
            SELECT enumlabel
            FROM pg_enum
            JOIN pg_type ON pg_enum.enumtypid = pg_type.oid
            WHERE pg_type.typname = 'paymentmethod'
        """)
    ).fetchall()

    enum_values = {row[0] for row in enum_values}

    if "WALLET" not in enum_values:
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE paymentmethod ADD VALUE 'WALLET'")

    # 2️⃣ Safely drop phone_number column (only if it exists)
    columns = {col["name"] for col in inspector.get_columns("users")}

    if "phone_number" in columns:
        op.drop_column("users", "phone_number")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # NOTE: Postgres does not support removing values from ENUM types easily
    # ### end Alembic commands ###
