"""add google refresh token to user

Revision ID: d40c0da79e77
Revises: 3267c5f395e9
Create Date: 2026-02-01 01:55:54.763790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40c0da79e77'
down_revision: Union[str, None] = '3267c5f395e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###
